/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestPageRouteImport } from './routes/testPage'
import { Route as Page2RouteImport } from './routes/page2'
import { Route as PageRouteImport } from './routes/page'
import { Route as IndexRouteImport } from './routes/index'

const TestPageRoute = TestPageRouteImport.update({
  id: '/testPage',
  path: '/testPage',
  getParentRoute: () => rootRouteImport,
} as any)
const Page2Route = Page2RouteImport.update({
  id: '/page2',
  path: '/page2',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page': typeof PageRoute
  '/page2': typeof Page2Route
  '/testPage': typeof TestPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page': typeof PageRoute
  '/page2': typeof Page2Route
  '/testPage': typeof TestPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page': typeof PageRoute
  '/page2': typeof Page2Route
  '/testPage': typeof TestPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page' | '/page2' | '/testPage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page' | '/page2' | '/testPage'
  id: '__root__' | '/' | '/page' | '/page2' | '/testPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  Page2Route: typeof Page2Route
  TestPageRoute: typeof TestPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testPage': {
      id: '/testPage'
      path: '/testPage'
      fullPath: '/testPage'
      preLoaderRoute: typeof TestPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page2': {
      id: '/page2'
      path: '/page2'
      fullPath: '/page2'
      preLoaderRoute: typeof Page2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  Page2Route: Page2Route,
  TestPageRoute: TestPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
